/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "us-west-2",
    "aws_cognito_identity_pool_id": "us-west-2:6fb5cfdf-409d-4d97-8bc7-3c68a1554b0d",
    "aws_cognito_region": "us-west-2",
    "aws_user_pools_id": "us-west-2_3fLE29PFa",
    "aws_user_pools_web_client_id": "1e1jhp0r0ohk0d4kd4k5jpbkac",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://safjgotsczcypapk5hauvm2dom.appsync-api.us-west-2.amazonaws.com/graphql",
    "aws_appsync_region": "us-west-2",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_appsync_apiKey": "da2-y45cvg6abbhdxbb44owtqwykeu",
    "aws_cloud_logic_custom": [
        {
            "name": "AdminQueries",
            "endpoint": "https://soqavjki6h.execute-api.us-west-2.amazonaws.com/dev",
            "region": "us-west-2"
        }
    ]
};


export default awsmobile;
